### ISSUE TITLE
Is this the repository related to "Extracting LLVM IR from Binary Code"?

### ISSUE THREAD

**Issue by mewmew** [allvm/allvm-tools#28]
Hi!

I recently came across the binary translation project at https://publish.illinois.edu/allvm-project/ongoing-research/

Is this the repository hosting code related to the "Extracting LLVM IR from Binary Code" research project? If so, is there a point of entry for documentation?

With kind regards,
Robin

**Comment by sdasgup3** [comment]
Dear @mewmew , the code for binary to llvm resides in a private repository and soon we will be open sourcing the project. In the mean while please have a look at  
[link](http://web.engr.illinois.edu/~sdasgup3/Document/allin_poster.pdf
)
Let me know in case  you need any other information.

**Comment by mewmew** [comment]
Hi Sandeep,

Glad to hear from you, and thanks for the link to the slides! I've actually read the slide you posted to before :)

> The code for binary to llvm resides in a private repository and soon we will be open sourcing the project

Wonderful to hear it will be open sourced soon! I'll be awaiting it with anticipation. Please let me know when. Do you have a preliminary release date in mind?

>  Let me know in case you need any other information.

I have many aspects of the architecture I'm curious about, but will wait with the questions until the code is released as open open source, and I can take it out for a spin.

Really glad you are working on this!

Kindly,
Robin

**Comment by sdasgup3** [comment]
Dear Robin(@mewmew),  I am planning to release the code for stack deconstruction at the end of  this month. I am happy to share it with you even before (via email, with all build instructions). 
Feel free to reach me at sdasgup3@illinois.edu

**Comment by dtzWill** [comment]
I think this is now available, or will be soon at this location: https://github.com/sdasgup3/binary-decompilation

Closing as resolved accordingly.  Good luck, enjoy!
